### ISSUE TITLE
Upload to shared assets folder

### ISSUE THREAD

**Issue by tracek** [tracek/gee_asset_manager#9]
Currently the tool assumes user uploads the data to his own folder. It should be able to recognise when the path leads to a shared folder and don't assume current user path.

**Comment by rbhargava2** [comment]
Where should we give the path to shared folder? 
I am inputting something like: 
geebam upload -u projects/servir-mekong -d C:\ET_Data\test_upload -m C:\ET_Data\test_upload\test_metadata.csv

Please let me know if I am inputting it correctly

**Comment by tracek** [comment]
That's the '-c' (collection) switch. Just provide fully qualified name to the folder, e.g. users/someuser/sharedfolder/myname

**Comment by rbhargava2** [comment]
![_github](https://cloud.githubusercontent.com/assets/23130293/19907676/10fcc648-a03d-11e6-8d46-1d568809c3f5.PNG)
Hey there! 
Thanks for your prompt reply. My issue is, the root of the shared asset is simply projects/servir-mekong and it is not nested under users/my_username so I get this error while using the switch : ee.ee_exception.EEException: Asset 'users/radb06/projects' does not exist.

here are the commands for the two tries I did: 
 geebam upload -u radb.06@gmail.com -c projects/servir-mekong  -d C:\ET_Data\test_upload -m C:\ET_Data\test_upload\test_metadata.csv

geebam upload -u radb.06@gmail.com -c users/radb06/projects/servir-mekong  -d C:\ET_Data\test_upload -m C:\ET_Data\test_upload\test_metadata.csv

Both of those gave me the same error. 
As always, thank you so much for your continued support, really appreciate it.

**Comment by tracek** [comment]
Try this:
geebam upload -u radb.06@gmail.com -c projects/servir-mekong/myawsomecollection -d C:\ET_Data\test_upload -m C:\ET_Data\test_upload\test_metadata.csv

projects/servir-mekong is the name of shared folder; you still need to provide a name for a collection

If it does not work, it would be best if you shared with me any (empty) folder in your assets, so that I could check the mechanism.

**Comment by rbhargava2** [comment]
It still gives the same error even after giving the name to the collection : ee.ee_exception.EEException: Asset 'users/radb06/projects/servir-mekong' does not exist.

here is an example of an image that sits under this shared folder : projects/servir-mekong/Classification/some_image

So you see, the root of this folder doesn't include my username. May be that's an issue? I'll try to share the folder with you if I have the rights to.

**Comment by rbhargava2** [comment]
I have shared an empty folder inside the shared folder with you. Let me know if you are able to access it.

**Comment by tracek** [comment]
Crap, it's me - i.e. my bug. Somehow I was always assuming that the path
starts with users/ and forgotten about that. Will fix right away.

**Comment by rbhargava2** [comment]
haha, I thought that's what it was. But you are awesome to figure it out. I'll try it out again tomorrow morning and will let you know how it goes. Do I need to update geebam after this change? I am not using a virtualenv. 
Also, thanks for answering such silly questions of mine, have just starting playing with any kind of technical work/ programming a couple months ago. I love it but just takes a lot of learning at every step!

Thanks again!

**Comment by tracek** [comment]
Thanks for help with troubleshooting! Can you provide me a full path to the
directory you have shared with me? I gather it's somewhere in
'projects/servir-mekong',
but what's the name of the directory?

And yeah, you will have to update. You can of course just grab the files I
am changing: geebam and batch_uploader.

**Comment by rbhargava2** [comment]
Hey there! 
I shared the projects/servir-mekong/ET  folder with out. 
Let me know if that helps! 
Regarding the update,  I have another silly question to ask. I was just going to uninstall geebam using pip and go through the installation process as you have described here. Or is there an easier way to update like pip update geebam?  (am just making it up,  I am not sure if something like that exists?) 

Thanks again! Please let me know when the files are ready to be used.

**Comment by tracek** [comment]
Hi!

By far the easiest method to update is via github. You just "pull" any
changes. If you are going to stick with programming for a while, learning a
few basic git commands is a must. It will make your life much easier!
Python is quite fun and easy to learn.

As for the shared folder, it looks like I don't have access to it - and I
tried also via browser. The folder is not visible also on GEE Playground.
You have used this email address, right?

BTW - cool project!

Lucas

**Comment by rbhargava2** [comment]
Hi Lucas, 
Thanks for the suggestions. I will do that! 
I used your gmail  : 	lukasz.tracewski@gmail.com
 
I added you again and it should be available now, please try again and let me know!

Also, are the changes updated? I can try uploading at my end too if that helps. 

and thanks, yeah it's going to be big!
Radhika

**Comment by tracek** [comment]
Wierd. Perhaps it's in a separate space? I shared with you users/rspb/test
- wonder if you see my directory.

Anyway, I pushed the changes to a separate branch:
https://github.com/tracek/gee_asset_manager/tree/absolute_path

You need to use '-p' switch.

Cheers,
Lucas

**Comment by rbhargava2** [comment]
Awesome!
I'll try it first thing in the morning and will update. Exciting!
but yeah, I don't see what you shared with me, it's very weird. 

Anyways, thanks for all your support, really appreciate it. 
Will post any updates here, tomorrow!
Cheers!
Radhika

**Comment by rbhargava2** [comment]
Hi Lucas!
I was trying to clone the new changes by using 
 git clone https://github.com/tracek/gee_asset_manager/tree/absolute_path

It gave me an error saying it can't find this path. So I just uninstalled geebam and reinstalled the whole set up again but I still can't use the -p switch, it says its not available. 

Do you have any suggestions on how should I incorporate the new changes? 
Thanks!

**Comment by tracek** [comment]
No need to uninstall anything. Just switch branch with git. As I said,
learning git basics is almost inevitable with programming :).

Cheers,
Lucas
